services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./pretrained_models:/app/pretrained_models
      - ./audios:/app/audios
      - ./reference_embeddings:/app/reference_embeddings